name: dotnet CI build

on:
  push:
    branches:
      - main

jobs:
  donet-ci-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/BluEye-Robotics/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build project and generate NuGet package
        run: |
          dotnet pack WaterLinked.UGPS/WaterLinked.UGPS.csproj --version-suffix "ci.$GITHUB_RUN_NUMBER" -c Release -o out

      - name: Push generated package to GitHub registry
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols --api-key $NUGET_AUTH_TOKEN